version: '3'
services:
  frontend:
    container_name: frontendapp
    build:
      context: ./react-module
      dockerfile: Dockerfile
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    networks:
      - moviesocial
    environment:
      - REACT_APP_APIURL=http://localhost:5000
    depends_on: 
      - web
  web:
    container_name: apiapp
    restart: always
    build: 
        context: ./api
        dockerfile: Dockerfile
    ports:
      - "5000:3000"
    environment:
      - DBNAME=mongodb+srv://root:root@cluster0.l8l09.mongodb.net/moviesocial?retryWrites=true&w=majority
      - PORT=3000
      - JWT_TOKEN=herg897qwerty654321
    volumes: 
      - ./api:/api
    networks:
        - moviesocial
networks: 
  moviesocial:
      driver: bridge